services:
  web:
    container_name: 'mock_service'
    build: .
    ports:
      - '8000:8000'
    volumes:
      - .:/code
    networks:
        - rabbitmq_web_net
    entrypoint: run-mock-service

  rabbit:
    image: rabbitmq:3.13-rc-management
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 15s
      timeout: 15s
      retries: 3
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_web_net

  rabbit_service:
    container_name: 'mock_rabbit_service'
    build: .
    depends_on:
      rabbit:
        condition: service_healthy
        restart: true
    ports:
      - '8080:8080'
    volumes:
      - .:/code
    networks:
      - rabbitmq_web_net
    entrypoint: run-mock-rabbitmq


networks:
  rabbitmq_web_net:
    driver: bridge
