on:
  pull_request:
    branches:
    - main
    - test

jobs:
  pr_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Check if the code pass all the tests and meet the style requirements
        run: pylint --rcfile=.pylintrc.toml manager_extension
